### ISSUE TITLE
Rocket Construction

### ISSUE THREAD

**Issue by ThomasGartman** [zatkins-school/BitsPlease-FESP#25]
We need a place to create rockets with different components

I feel the work required for this will be fairly extensive:

  

- [x] Render a categorized list of rocket components
    - [x] e.g. Fuel Tanks, Engines, SAS (Control & RCS), Parachutes, Landing Gear, stage breaks
- [x] Allow selection and placement of these components on some central pane
- [ ] Find some way to attach specific components (e.g. engines to fuel tanks)
- [ ] In the future, also allow programming of staging
- [x] Take the assembled rocket, and pass it along to the simulation.

Implementation Ideas:

- Component List:
    - Before we can render a list of components, we need more components. Each different component should have its own class, so multiple components of one type can be made. So if we wanted to have 5 different engines in the game, we would have 6 classes. One for each engine, and then one engine class for them to inherit from in common.
- Central building pane:
    - One idea is to have a pymunk space where time never moves, i.e. we never call space.step(). This way our non-static rocket parts can be placed without worrying about gravity, or user input.
This may not work, if a frozen pymunk space doesn't allow things to move by manually changing its position. If this is the case, another option would be to create a rocket object and call Body.sleep() on it. The docs don't describe exactly what "sleeping" is, but if it stops processing physics on the body then it would suffice
    - If none of these can be done, then we can abstract control away from the components themselves, and then create some upper controller class that will implement user control of the rocket and rocket parts. We can simply not instantiate this controller for the rocket-building section to avoid messing with the rocket.
- Attaching components:
    - My current thoughts on this are to not to necessarily associate individual components, but rather to pool their resources. There would have to be some kind of priority here, so fuel tanks of a later stage won't be drained by fuel tanks from the current stage. Implementation of this in game will be done elsewhere, but here simply assigning a stage number to a part will suffice (or somehow generating this based on placement relative to some stage separator).
- Stage Programming:
    - The best way to do this would be to set the stage number of a component based on its position relative to a stage separator. If this isn't feasible, then setting a stage number manually may be required.
- Passing rocket to sim:
    - This bit shouldn't be too hard. The rocket builder will be operating on an instance of a rocket, which as a body we should be able to deep copy. We may need to implement our own copy function to carry over component information. This body copy can then be passed to the simulation and ran.

**Comment by Gagerdude** [comment]
I feel the work required for this will be fairly extensive:
- [ ] Render a categorized list of rocket components
  * e.g. Fuel Tanks, Engines, SAS (Control & RCS), Parachutes, Landing Gear, stage breaks
- [ ] Allow selection and placement of these components on some central pane
- [ ] Find some way to attach specific components (e.g. engines to fuel tanks)
- [ ] In the future, also allow programming of staging
- [ ] Take the assembled rocket, and pass it along to the simulation.

Implementation Ideas:
 - Component List:
   - Before we can render a list of components, we need _more_ components. Each different component should have its own class, so multiple components of one type can be made. So if we wanted to have 5 different engines in the game, we would have 6 classes. One for each engine, and then one engine class for them to inherit from in common.
 - Central building pane:
   - One idea is to have a pymunk space where time never moves, i.e. we never call space.step(). This way our non-static rocket parts can be placed without worrying about gravity, or user input.
   - This may not work, if a frozen pymunk space doesn't allow things to move by manually changing its position. If this is the case, another option would be to create a rocket object and call Body.sleep() on it. The docs don't describe exactly what "sleeping" is, but if it stops processing physics on the body then it would suffice
   - If none of these can be done, then we can abstract control away from the components themselves, and then create some upper controller class that will implement user control of the rocket and rocket parts. We can simply not instantiate this controller for the rocket-building section to avoid messing with the rocket.
 - Attaching components:
   - My current thoughts on this are to not to necessarily associate individual components, but rather to pool their resources. There would have to be some kind of priority here, so fuel tanks of a later stage won't be drained by fuel tanks from the current stage. Implementation of this in game will be done elsewhere, but here simply assigning a stage number to a part will suffice (or somehow generating this based on placement relative to some stage separator).
 - Stage Programming:
   - The best way to do this would be to set the stage number of a component based on its position relative to a stage separator. If this isn't feasible, then setting a stage number manually may be required.
 - Passing rocket to sim:
   - This bit shouldn't be too hard. The rocket builder will be operating on an instance of a rocket, which as a body we should be able to deep copy. We may need to implement our own copy function to carry over component information. This body copy can then be passed to the simulation and ran.

**Comment by Gagerdude** [comment]
Perhaps it would also be better to have a separate rocket builder class that has its own event loop.
